#!/bin/bash
cd `dirname ${BASH_SOURCE[0]}`
java -Xmx512m -cp bin;NullpoMino.jar:lib/log4j.jar:lib/swing-worker.jar:lib/swing-layout.jar -Djava.library.path=lib mu.nu.nullpo.tool.airankstool.AIRanksTool
